---
title: "project"
author: "czycs"
date: '2022-10-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read:
```{r message=FALSE, paged.print=FALSE}
source("2022_10_30_read_data.R")
```

```{r}
berlin_neigh <- geojsonio::geojson_read("Berlin/2022_09_15_Berlin_neighbourhoods.geojson", what = "sp")
# 'fortify' the data to get a dataframe format required by ggplot2
berlin_fortified <- tidy(berlin_neigh)
ggplot() +
  geom_polygon(data = berlin_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  coord_map()

```

```{r}
munich_neigh <- geojsonio::geojson_read("Munich/2022_09_21_Munich_neighbourhoods.geojson", what = "sp")
# 'fortify' the data to get a dataframe format required by ggplot2
munich_fortified <- tidy(munich_neigh)

ggplot() +
  geom_polygon(data = munich_fortified, aes( x = long, y = lat, group = group), fill="#69b3a2", color="white") +
  geom_point(data = munich_listings, x = munich_listings$longitude, y=munich_listings$latitude, size=0.5) +
  coord_map()
```
Kenngrößen

```{r}
# Number of listings
length(berlin_listings$id)
length(munich_listings$id)

# number of diiferent hosts
length(unique(berlin_listings$host_id))
length(unique(munich_listings$host_id))

# mean price 
mean(berlin_listings$price)
mean(munich_listings$price)

# median price

median(berlin_listings$price)
median(munich_listings$price)

# max min
tail(sort(berlin_listings$price))
tail(sort(munich_listings$price))

head(sort(berlin_listings$price))
head(sort(munich_listings$price))

# 0 price
berlin_listings_full[which(berlin_listings_full$price==0),]$listing_url


```


Ausstattung
```{r}
test <- list(berlin_listings_full$amenities)
test <- sapply(test, function(x) gsub('\"', "", x, fixed = TRUE))
test <- as.list(test)
test <- sapply(test, function(x) gsub('\\[|\\]', "", x))
test <- as.list(test)
test <- stri_unescape_unicode(test)
test <- as.list(test)
test <- str_split(test,", ")
#table(unlist(test))
length(unique(unlist(test)))

```
Reviews

```{r}
dt <- berlin_listings_full[which(berlin_listings_full$review_scores_rating==0),]
dt1 <- dt <- berlin_listings_full[which(berlin_listings_full$number_of_reviews==0),]
```


Berlin Plots
```{r}
ggplot(data = berlin_listings_full, mapping = aes(y=price, 
                                                  x=review_scores_rating))+
  geom_point(size=0.5)
ggplot(data = berlin_listings_full, mapping = aes(y=price, 
                                                  x=number_of_reviews))+
  geom_point(size=0.5)
ggplot(data = berlin_listings_full, mapping = aes(x=review_scores_rating, 
                                                  y=number_of_reviews))+
  geom_point(size=0.5)
```

